### ISSUE TITLE
There is no data provider

### ISSUE THREAD

**Issue by Zolak94** [DaGhostman/vscode-tree-view#104]
I installed extension and when I click on File Symbol Explorer i get this message: 
> There is no data provider registered that can provide view data.

I want to use this extension on project where I'm using sftp connection to see all files. My project is made in Larave (PHP)

Extension details:

> Name: File Tree View
> Id: daghostman.vs-treeview
> Description: Tree View extension providing an overview of the main file symbols
> Version: 2.6.0
> Publisher: Dimitar Dimitrov
> VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=DaGhostman.vs-treeview

**Comment by DaGhostman** [comment]
I have never really tested the extension using a remote workspace honestly, although I think that it should be working just fine.

Could you try disabling all other extensions to see if any of the others is not interfering/crashing, I remember having such issues when an extension crashed and it was preventing other extensions from loading

**Comment by DaGhostman** [comment]
I will be closing this as there is insufficient information about it, please if you manage to identify pattern of the failures, please do let me know and I could try to give it another try
