### ISSUE TITLE
[JS] Class - set/get, module.exports - not listed

### ISSUE THREAD

**Issue by GregSpa** [DaGhostman/vscode-tree-view#105]
Hi,

Thank you for the extension. I find it very useful.

Do you thing is it possible to add support for set and get in the JS classes, that seem not to be listed in the tree.

What is not listed:

1. 

`module.exports = class MyClass {}`

2. set/get - 

```
class MyClass {
   constructor() {
      this.prop = 'Hello';
   }
   set prop(value) {
      this._prop = value;
   }
   get prop(){
      return this._prop;  
   }
}
```

Thank you,
Greg

**Comment by DaGhostman** [comment]
Hey, thanks for the issue. I've made some changes to #103 and add accessors to TS/JS, but unfortunately the TS parser doesn't seem to pick up the `modules.export` syntax :disappointed: I will continue to look into that one, but recently work has kept me too occupied

**Comment by DaGhostman** [comment]
as it turns out, there is no reliable way to extract `module.exports` from the typescript parsers so for now that is a no-go, although it is something I will try to address if I get enough time to do so
