### ISSUE TITLE
Does not work for Python files

### ISSUE THREAD

**Issue by egabrum** [DaGhostman/vscode-tree-view#108]
Version [2.7.0]
.py files are not parsed.

**Comment by DaGhostman** [comment]
Hey, could you confirm that this is the case even for simple python files? Because I suspect this might be related to #100 i.e having/using syntax that is not supported by Filbert

**Comment by egabrum** [comment]
No, does not work.
Even for something as simple as

```#!/usr/bin/env python3
# -*- coding:utf-8 -*-

a = 1
b = 2

a, b = b, a
```

**Comment by DaGhostman** [comment]
this is the same sniper described https://github.com/DaGhostman/vscode-tree-view/issues/100#issuecomment-481080605

unfortunately I cat do anything about this, therefore closing as duplicate
