### ISSUE TITLE
Command Not found when refreshing

### ISSUE THREAD

**Issue by thanhluan88** [DaGhostman/vscode-tree-view#116]
I met a problem when clicking to refresh button. 
Do you know the root cause.
![image](https://user-images.githubusercontent.com/39419202/127727299-04681b39-72c2-4d1c-bdbc-be901b10f12e.png)

**Comment by d0ob** [comment]
Hi here !

So what was the problem ?

I have the same error when I try to refresh.
I also have this one when trying to pin : command 'extension.treeview.pin' not found
And those ones when trying any of the shortcut : command 'workbench.view.extension.symbol-treeview' not found 

What am I doing wrong ? I downloaded the ext, read multiple time the read-me and this github, added the setting, but I'm lost..
Is there a very noob friendly "how to" maybe ? An explicit step by step ?

Thanks !
