### ISSUE TITLE
[Feature] Java file parser

### ISSUE THREAD

**Issue by kubawolanin** [DaGhostman/vscode-tree-view#22]
Hi @DaGhostman!

It would be great addition if your extension supported Java files as well.
There's a Node package that does all the parsing for you. See [java-parser](https://www.npmjs.com/package/java-parser).

Keep up the good work!

**Comment by DaGhostman** [comment]
Thanks on suggesting the `java-parser` package, I was looking into adding java and C# support, but was not able to find independent parser for each one. Java support will come with the next release (#21 ) as there are some BCs and I don't see much point in adding it as a feature release only to have to overwrite it in a couple of days (I feel like the majority of the work is almost done).

**Comment by DaGhostman** [comment]
Implemented in latest release
