### ISSUE TITLE
[FR] freeze tree

### ISSUE THREAD

**Issue by Cologler** [DaGhostman/vscode-tree-view#89]
Is possible freeze the tree on one file when I need to switch between multi files ?

**Comment by DaGhostman** [comment]
Currently that is not supported, but updating the view on every switch to a new file is performed. But seems like an interesting idea tbh. Can you describe what you would like to see, if I get enough time in the weekend I will try to take a look if it can be implemented quickly

**Comment by Cologler** [comment]
like:

1. Open file A
1. Open tree view
1. click `keep current view` button
1. switch to file B, tree view has nothing changes (click any node from tree view will open file A)
1. click the button again, tree view go back to default behavior
