### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by ghost** [DaGhostman/vscode-tree-view#98]
- Issue Type: `Performance`
- Extension Name: `vs-treeview`
- Extension Version: `2.6.0`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\jk\DaGhostman.vs-treeview-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by DaGhostman** [comment]
Closing because of lack of information
