### ISSUE TITLE
How to use this extension to view the structure of the c/cpp file

### ISSUE THREAD

**Issue by JeffYoung17** [DaGhostman/vscode-tree-view#99]
In the README.md, what does this description mean?
`They are also disabled by default and need to be enabled by adding cfamily to the treeview.allowedProviders array. `

 Where is the `treeview.allowedProviders array`?

**Comment by DaGhostman** [comment]
I am sorry for the late response, that array is located in the configuration of vscode, IMO you will not be able to do it through the Settings interface, but instead you will need to add `cfamily` to the `settings.json` under the key `treeview.allowedProviders`

**Comment by JeffYoung17** [comment]
thanks!!
